import { NextRequest, NextResponse } from 'next/server';
import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';

const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY || '';
const FROM_EMAIL = 'noreply@sourcepilot.cn';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

// 获取当前用户会话
async function getSession() {
  const cookieStore = await cookies();
  
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value;
        },
        set() {},
        remove() {},
      },
    }
  );

  const { data: { session } } = await supabase.auth.getSession();
  return session;
}

// 翻译文本
const t = {
  en: {
    subject: 'Your SourcePilot Sourcing Report',
    greeting: 'Hello',
    intro: 'Here is your sourcing report from SourcePilot.',
    items: 'Selected Items',
    price: 'Price',
    shop: 'Shop',
    view: 'View Product',
    footer: 'This report was generated by SourcePilot'
  },
  zh: {
    subject: '您的 SourcePilot 采购报告',
    greeting: '您好',
    intro: '这是您从 SourcePilot 生成的采购报告。',
    items: '选中商品',
    price: '价格',
    shop: '店铺',
    view: '查看商品',
    footer: '本报告由 SourcePilot 生成'
  },
  ar: {
    subject: 'تقرير التوريد الخاص بك من SourcePilot',
    greeting: 'مرحباً',
    intro: 'إليك تقرير التوريد الخاص بك من SourcePilot.',
    items: 'العناصر المحددة',
    price: 'السعر',
    shop: 'المتجر',
    view: 'عرض المنتج',
    footer: 'تم إنشاء هذا التقرير بواسطة SourcePilot'
  },
  ru: {
    subject: 'Ваш отчет о закупках SourcePilot',
    greeting: 'Здравствуйте',
    intro: 'Вот ваш отчет о закупках от SourcePilot.',
    items: 'Выбранные товары',
    price: 'Цена',
    shop: 'Магазин',
    view: 'Просмотреть товар',
    footer: 'Этот отчет сгенерирован SourcePilot'
  },
  es: {
    subject: 'Su informe de abastecimiento SourcePilot',
    greeting: 'Hola',
    intro: 'Aquí está su informe de abastecimiento de SourcePilot.',
    items: 'Artículos seleccionados',
    price: 'Precio',
    shop: 'Tienda',
    view: 'Ver producto',
    footer: 'Este informe fue generado por SourcePilot'
  }
};

export async function POST(request: NextRequest) {
  try {
    const session = await getSession();
    
    if (!session) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const body = await request.json();
    const { items, to, lang = 'en' } = body;

    if (!items || !Array.isArray(items) || items.length === 0) {
      return NextResponse.json(
        { error: 'No items selected' },
        { status: 400 }
      );
    }

    if (!to) {
      return NextResponse.json(
        { error: 'Recipient email is required' },
        { status: 400 }
      );
    }

    const text = t[lang as keyof typeof t] || t.en;

    // 构建HTML内容
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${text.subject}</title>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #2563eb; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
    .item { display: flex; gap: 20px; margin-bottom: 30px; padding: 20px; border: 1px solid #e5e7eb; border-radius: 8px; }
    .item img { width: 120px; height: 120px; object-fit: cover; border-radius: 8px; }
    .item-info { flex: 1; }
    .item-title { font-weight: bold; font-size: 18px; margin-bottom: 8px; }
    .item-price { color: #dc2626; font-size: 20px; font-weight: bold; }
    .item-shop { color: #6b7280; font-size: 14px; }
    .btn { display: inline-block; padding: 10px 20px; background: #2563eb; color: white; text-decoration: none; border-radius: 6px; margin-top: 10px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; text-align: center; }
  </style>
</head>
<body>
  <h1>${text.subject}</h1>
  <p>${text.greeting},</p>
  <p>${text.intro}</p>
  
  <h2>${text.items} (${items.length})</h2>
  
  ${items.map(item => `
    <div class="item">
      <img src="${item.image_url}" alt="${item.title}">
      <div class="item-info">
        <div class="item-title">${item.title}</div>
        <div class="item-price">¥${item.price}</div>
        <div class="item-shop">${text.shop}: ${item.shop_name}</div>
        <a href="${item.pid_link || item.product_url}" class="btn" target="_blank">${text.view}</a>
      </div>
    </div>
  `).join('')}
  
  <div class="footer">
    ${text.footer} | ${new Date().toLocaleString()}
  </div>
</body>
</html>
    `;

    // 发送邮件
    const response = await fetch('https://api.sendgrid.com/v3/mail/send', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${SENDGRID_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        personalizations: [{
          to: [{ email: to }]
        }],
        from: { email: FROM_EMAIL, name: 'SourcePilot' },
        subject: text.subject,
        content: [{
          type: 'text/html',
          value: htmlContent
        }]
      })
    });

    if (!response.ok) {
      const errorData = await response.text();
      console.error('[PDF Send] SendGrid error:', errorData);
      return NextResponse.json(
        { error: 'Failed to send email' },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      message: 'Email sent successfully'
    });

  } catch (error) {
    console.error('[PDF Send] Error:', error);
    return NextResponse.json(
      { error: 'Failed to send email' },
      { status: 500 }
    );
  }
}
